// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package id

type UserInvitationRequest struct {
	ID     string `json:"id" gorm:"primary_key"`
	UserID string `json:"userId" gorm:"primary_key"`
}
type UserActivationRequest struct {
	ID     string `json:"id" gorm:"primary_key"`
	UserID string `json:"userId" gorm:"primary_key"`
}
type ForgotPasswordRequest struct {
	ID     string `json:"id" gorm:"primary_key"`
	UserID string `json:"userId" gorm:"primary_key"`
}
